version: '3.8'

services:
  tts-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tts-bot
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./pdfs:/app/pdfs